from pathlib import Path
import importlib.util
import json

from src.ulog.parsers.cv import CVParser


def _load_cv_generator():
    # Load module from file to avoid package import issues
    path = Path("data/generator/cv_generator.py").resolve()
    # Ensure the data/generator directory is on sys.path so internal imports ("from generator import ...") work
    import sys

    gen_dir = str(path.parent)
    if gen_dir not in sys.path:
        sys.path.insert(0, gen_dir)

    spec = importlib.util.spec_from_file_location("cv_generator", str(path))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.GenerateCVLog


def test_cv_parse_acceptance_rate():
    """Generate a deterministic CV sample and assert parse acceptance >= 95%."""
    GenerateCVLog = _load_cv_generator()

    fields = [
        "phase",
        "model_name",
        "dataset_id",
        "image_count",
        "metrics",
        "latency_ms",
        "batch_size",
        "hardware",
        "outcome",
    ]

    valid_params = ["timestamp", "component", "safety_flag", "category", "level", "ok"]

    # Use a fixed seed for reproducibility and a reasonably sized sample
    gen = GenerateCVLog(fields, size=200, seed=12345, input_params=[], valid_params=valid_params)

    valid_logs, invalid_logs = gen.run()

    parser = CVParser()
    total = 0
    success = 0

    for log in valid_logs:
        total += 1
        raw = None
        try:
            raw = log.get("meta", {}).get("raw_message")
        except Exception:
            raw = None
        if raw is None:
            # fallback to compact json representation
            raw = json.dumps(log, separators=(",", ":"))

        res = parser.parse(raw)
        if res.success:
            success += 1

    assert total > 0, "No logs were generated by the CV generator"
    success_pct = success / total

    # Expect at least 95% of generated valid CV raw messages to be parsable
    assert success_pct >= 0.95, f"Parse acceptance too low: {success_pct:.2%} (<95%)"
